# Generated by Django 2.0.2 on 2018-04-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_comment_comments_comment_author'),
        ('help_Qna', '0002_auto_20180404_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpqna',
            name='Help_Qna_Comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helpqnas', to='Comments.Comments'),
        ),
    ]
