# Generated by Django 2.0.2 on 2018-04-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_subcategory', '0002_auto_20180404_1258'),
        ('location_pitch', '0002_auto_20180404_1258'),
        ('Location_Category', '0002_auto_20180404_1258'),
        ('Quick_Requirements', '0002_auto_20180404_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick_requirements',
            name='Quick_Requirements_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Location_Category.Location_Category'),
        ),
        migrations.AddField(
            model_name='quick_requirements',
            name='Quick_Requirements_Pitch_List',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitchlist', to='location_pitch.LocationPitch'),
        ),
        migrations.AddField(
            model_name='quick_requirements',
            name='Quick_Requirements_Sub_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locationsubcategory', to='location_subcategory.LocationSubCategory'),
        ),
    ]
