# Generated by Django 2.0.2 on 2018-04-04 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('Prop', '0002_auto_20180404_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='Prop_Images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='image.Image'),
        ),
    ]
