# Generated by Django 2.0.2 on 2018-04-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_subcategory', '0002_auto_20180404_1258'),
        ('help_category', '0002_auto_20180404_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='help_category',
            name='Help_SubCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helpsubcategorys', to='help_subcategory.HelpSubCategory'),
        ),
    ]
