# Generated by Django 2.0.2 on 2018-04-04 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_Comment', models.CharField(max_length=150)),
                ('Video_Comment_Created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_My_Video', models.FileField(max_length=200, upload_to='video/')),
                ('Video_Owned_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Videocommentss', to='Video.Video'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Video_Comment_Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Videocomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
