# Generated by Django 2.0.2 on 2018-04-04 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer_contact', '0002_auto_20180404_1258'),
        ('Location_Authorities', '0002_auto_20180404_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationauthority',
            name='Location_Authority_Contact_Officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Officercontact', to='officer_contact.OfficerContact'),
        ),
    ]
